Roleplay inventory
esrg-knights/Squire pull request #119
Opened 2021-08-09 14:15 UTC by DutcherNL

I keep going, but this is the end stop. No more new PRs after this for at least 2 weeks.

Oh yeah, I added a roleplay system branch on the system with an implementation of the new inventory system.

2021-08-10 13:28 UTC, EricTRL requested changes
I like the changes! :D
However, I feel like navigation between roleplay systems, their items, its catalogue, and its edit pages is a bit finnicky. Sometimes there's a button to go somewhere, but none to go back. As a result, I ended up clicking back-and-forth through several pages before I got to the page where I wanted to go to.
The navigation seems a tad bit different from the boardgame-navigation due to the introduction of the "systems"-page, which is probably why I'm having trouble.

Other than that there are few, mostly minor, points of feedback or suggestions.

2021-08-10 13:28 UTC, EricTRL commented on inventory/urls.py
> +            # item_type = ContentType.objects.get()
These things always manage to sneak in :P

2021-08-10 13:28 UTC, EricTRL commented on roleplaying/migrations/0001_squashed_initial.py
> +    replaces = [('roleplaying', '0001_initial'), ('roleplaying', '0002_auto_20210803_0009'), ('roleplaying', '0003_roleplayingitem_digital_version_file_name'), ('roleplaying', '0004_roleplayingsystem
This isn't really needed as these migrations aren't in production

2021-08-10 16:28 UTC, DutcherNL reviewed
Reply

2021-08-13 11:15 UTC, EricTRL approved these changes

2021-08-13 11:31 UTC, EricTRL submitted a review, later dismissed

2021-08-13 11:53 UTC, EricTRL approved these changes

2021-08-13 11:56 UTC, merged