Add change account information feature
esrg-knights/Squire pull request #203
Opened 2021-12-03 15:20 UTC by waiterorg

![Screenshot](https://user-images.githubusercontent.com/63255329/144626920-72cd5304-1697-4b13-85a7-7770a9148950.png)
![ScreenshotEdit](https://user-images.githubusercontent.com/63255329/144626947-e7781d88-440e-4dee-9447-4cddc5170f69.png)

2021-12-03 15:27 UTC, DutcherNL commented
Having fun with out codebase I see :D

May I ask how you found us and what your interest is in our code?

2021-12-03 20:15 UTC, waiterorg commented
I was looking for an interesting project in github
I saw your project and checked it, sound interesting knights board game and roleplaying to me
I wanted to contribute on your project :)

2021-12-03 20:22 UTC, DutcherNL commented
Yeah, we are a student association in Eindhoven, the Netherlands, devoted to board- and roleplaying games. Squire is our internal platform where we track our membership as well as our board- and roleplaying collection. It's a hodge podge of features that we deemed useful right now :)
While we do appreciate your contribution, we'd like to wait a bit till we are done and implemented with #197. It combines the several personal pages into one navigatable layout and also results in some code being shifted around, including the bit where you are implementing this. I hope you can understand that.

2021-12-03 20:36 UTC, waiterorg commented
That's ok, thank you so much for your explain
I wish best for your team and your platform :)

2021-12-05 11:22 UTC, EricTRL requested changes
As @DutcherNL already mentioned, thank you for your contribution. We appreciate it! Now that #197 has been merged we're ready to tackle this feature! Quite some code has moved around, so do ask for help if you're having trouble with finding the relevant files and folders. 

Note that the core of your PR (e.g., the view, form, or templates you created) is still standing strong, and to get this thing running on master will _mostly_ involve moving code around to different files. Again, if you're having trouble with that, do ask for help!

I've also added some specific feedback, which are mostly minor changes.

2021-12-05 11:22 UTC, EricTRL commented on core/views.py
> +        return self.request.user
I'd argue that you can move `get_object` straight to `AccountChangeView` as it's not used anywhere else. Furthermore, `AccountChangeview` can then directly inherit `LoginRequiredMixin`

2021-12-05 11:22 UTC, EricTRL commented on core/views.py
> +    permission_required = ('core.can_view_account_information_self', 'core.can_change_account_information_self')
These permissions don't actually exist. I suspect that you took the membership change view as a reference point for your changes, which do require specific permissions which do exist. Note how we create those in the model `membership_file.models.Member` using that model's [Meta option for `permissions`](https://docs.djangoproject.com/en/2.2/ref/models/options/#permissions)

Either way, I don't think we would want to limit account editing through permissions, so I'd suggest to remove `PermissionRequiredMixin` and its corresponding required permissions:
```suggestion

```

2021-12-05 11:22 UTC, EricTRL commented on core/views.py
> +        message = _("Your account information has been saved successfully! Notice the name disappears when the user is a membership ")
The name-hiding for members is basically an ugly hack on our side; there's no need to mention that to our members
```suggestion
        message = _("Your account information has been saved successfully!")
```

2021-12-05 11:22 UTC, EricTRL commented on core/forms.py
> +
It's possible to replace the 'first_name' field label by custom text in a [modelform's meta options](https://docs.djangoproject.com/en/3.2/topics/forms/modelforms/#overriding-the-default-fields). For instance, we can change it to match the field name to how it shows up when a user registers:
```suggestion
    labels = {
        'first_name': 'Real Name',
    }
        
```

2021-12-16 13:00 UTC, waiterorg commented
Sorry for taking so long to do this actions, thank you so much for your feedback, I did changes which you requested.

2021-12-16 13:03 UTC, DutcherNL commented
Not a problem. Just take your time, we do too :)
I do notice that there are still some conflicts that need to be resolved, can you resolve those so we can look at them this weekend?

2021-12-16 13:56 UTC, waiterorg commented
what conflicts?
if you know can you tell me please ?

2021-12-16 13:58 UTC, DutcherNL commented
At the bottom of this page, github says taht the branch has conflicts with the master that must be resolved. It applies to:
core/templates/core/user_accounts/account_info.html
core/urls.py
core/views.py

2021-12-16 15:41 UTC, EricTRL requested changes
It seems like some things went wrong during the merge as there are some merge conflicts left. I left some review suggestions on how to solve those. :)

I've also enabled the test runner for this PR.
And as Dutcher already mentioned: Don't worry about taking your time. We're doing this as a side-project and there's no rush involved whatsoever :)

2021-12-16 15:41 UTC, EricTRL commented on core/urls.py
> +<<<<<<< HEAD
The account and password-change urls have been moved to `user_interaction/account_pages/config.py`. The account-change url can be moved there as well.

2021-12-16 15:41 UTC, EricTRL commented on core/views.py
> +<<<<<<< HEAD
To resolve these import conflicts, I'd suggest to keep the imports from both your branch and those from master.

2021-12-16 15:41 UTC, EricTRL commented on core/views.py
> +<<<<<<< HEAD
`AccountTabsMixin` actually no longer exists with the new setup. You can move your `AccountChangeView` to `user_interaction/account_pages/views.py` and have your `AccountChangeView` inherit from `AccountViewMixin` instead as well (see how this is done for `SiteAccountView` for instance)

2021-12-16 15:43 UTC, EricTRL commented on core/views.py
> +        message = message = _("Your account information has been saved successfully!")
This change also seems like a small error (note the extra `message =`

2021-12-16 20:41 UTC, waiterorg commented
Sorry about pervious commit .
I change view , form, template but i  could not figure out where i can implement url .

2021-12-17 15:38 UTC, EricTRL requested changes
A few issues regarding the moving around of URLs (note the failing test), but after this we're ready to merge!

2021-12-17 15:38 UTC, EricTRL commented on core/templates/core/user_accounts/account_edit.html
> +{% extends 'core/user_accounts/account_base.html' %}
This file is identical to the other `account_edit.html` file created in this PR. Feel free to remove this one as it's not actually used.

2021-12-17 15:38 UTC, EricTRL commented on user_interaction/templates/user_interaction/account_pages/account_edit.html
> +            {% generic_field form.email -1 %}>
There's an additional `>` at the end
```suggestion
            {% generic_field form.email -1 %}
```

2021-12-17 15:38 UTC, EricTRL commented on user_interaction/templates/user_interaction/account_pages/account_edit.html
> +            <p><i> You can change your password <a href="{% url 'core:user_accounts/password_change' %}">here</a></i></p>
The password-change url was moved
```suggestion
            <p><i> You can change your password <a href="{% url 'account:password_change' %}">here</a></i></p>
```

2021-12-17 15:38 UTC, EricTRL commented on user_interaction/templates/user_interaction/account_pages/account_edit.html
> +        href="{% url 'core:user_accounts/account' %}"
Same as above (and similar to the change you already made in `AccountChangeView.success_url`)
```suggestion
        href="{% url 'account:site_account' %}"
```

2021-12-17 15:38 UTC, EricTRL commented on user_interaction/templates/user_interaction/account_pages/site_account_page.html
> +        <small class="text-muted">To change your account information, click <a href="{% url 'core:user_accounts/account/edit' %}">here</a></small>
Same movement of urls as above
```suggestion
        <small class="text-muted">To change your account information, click <a href="{% url 'account:account_change' %}">here</a></small>
```

2021-12-17 15:38 UTC, EricTRL commented on user_interaction/account_pages/config.py
> +            path('account/edit', AccountChangeView.as_view(config=self), name='account_change'),
This causes a url of the form `/account/site/account/edit` (note the double "account"). We're also slowly transitioning to have all URLs should end with a trailing `/`.
```suggestion
            path('edit/', AccountChangeView.as_view(config=self), name='account_change'),
```

2021-12-17 19:07 UTC, waiterorg commented
Thank you so much for taking time to me and explaining !
I fixed urls , I was do wrong some places for not being fimiliar with the project :)
the account system has many changes from 10 days ago .
I hope everything will be fine this time !

2021-12-17 20:16 UTC, DutcherNL requested changes
We really appreciate your help here and it looks really good. Sorry for making you decypher the new structure, though hopefully the massive change does make it easier now to append things anywhere in the account tabs :)
Anyway, your code looks good. Just two minor points to note, one of which is more user-communication related (because we store the users name twice). If you could change that than I'll merge your PR asap :D

2021-12-17 20:16 UTC, DutcherNL commented on core/forms.py
> +        }
From a user experience perspective it is weird that we store the person name in two places (here and in membership). As long as we do though, we may need to inform the user on the way it differs. As such I propose the following addition:

```suggestion
        }
        help_texts = {
            'first_name': 'This name is not connected to the name registered on your membership. Once membership is linked, the site will use the name registered on your membership instead.',
        }
```

2021-12-17 20:16 UTC, DutcherNL commented on core/forms.py
> +class AccountForm(ModelForm):
Personally I'd rather see this particular form placed in `user_interaction/account_pages/forms.py` as this form will only be used in this section and thus is less relevant as part of the core. It's just a personal preference though

2021-12-18 09:50 UTC, waiterorg commented
Yes , the new structure seems better than before !
I changed that from .

2021-12-18 15:11 UTC, DutcherNL approved these changes

2021-12-18 15:18 UTC, DutcherNL commented
The code looks good. I'll join it later this weekend.

One note I want to add for any of your current or future projects is that we advice you to write testcases. I know it is boring and if all goes well you never need it, but I've had my fair share of accidentally breaking functionality without me noticing it that test cases are really useful to implement. In this project for instance there are quite a few unique cases when dealing with dates so having test cases helps us ensure that we did not break anything when we update a piece of code somewhere in the activity_calendar module.

For more information on testing in Django read this:
https://docs.djangoproject.com/en/2.2/topics/testing/

2021-12-19 09:10 UTC, waiterorg commented
I appreciate your advice , yes I completely with you !
I started testing and testcase a little while ago and I try to be better in test .
It makes me happy if you tell me your opinion about my test [in this demo project](https://github.com/waiterorg/WaiterShop/tree/main/WaiterShop/core/tests)

2021-12-19 10:21 UTC, EricTRL approved these changes
Looks good to me now, so time to merge! I also agree on @DutcherNL's comment regarding tests, but given the scale of this PR this is good enough for now!

Regarding the tests in your other project: they seem fine on a quick glance. You're also already using a library like `coverage.py` so you can check code coverage (which doesn't tell you everything about the quality of your tests, but does allow you to see which code lacks one).
I'd also recommend to integrate some Continuous Integration (CI) in that project to automatically run your tests on a push or pull request: it'll save you quite a lot of headaches if you accidentally break something! Travis is no longer free today, but GitHub Actions serves as a pretty much perfect alternative. You can look into the GitHub Actions we have for this repo in the `.github` folder for some inspiration :)

2021-12-19 10:21 UTC, merged

2021-12-20 10:42 UTC, waiterorg commented
I definitely take your advice , thank you !