Feature/nextcloud
esrg-knights/Squire pull request #287
Opened 2022-10-15 21:13 UTC by DutcherNL

Developing source code to synch Nextcloud with Django.

To do:

- [ ] Permissions to download
- [ ] Permissions to edit
- [ ] Uploading to Nextcloud
- [ ] General download page linked in header

Possible extentions:
- Connect NCFolder to activity (e.g. ALV including the files for that ALV)

2023-01-07 17:14 UTC, EricTRL commented on nextcloud_integration/templates/nextcloud_integration/snippets/nc_folder_contents.html
> +                    Folder missing on disk
```suggestion
                    Folder missing
```

2023-01-07 17:16 UTC, EricTRL commented on nextcloud_integration/templates/nextcloud_integration/snippets/nc_folder_contents.html
> +            {% if user|has_synch_access %}
```suggestion
            {% if perms.nextcloud_integration.synch_ncfile %}
```

2023-01-07 17:33 UTC, EricTRL commented on nextcloud_integration/widgets.py
> +    # def render(self, name, value, attrs=None, renderer=None):
:)

2023-01-08 16:34 UTC, DutcherNL commented on nextcloud_integration/views.py
> +            queryset = queryset.filter(requires_membership=False)
I will move some logic, including this mechanic to a groupconfig later on

2023-01-08 17:40 UTC, EricTRL commented on nextcloud_integration/models.py
> +        if SquireNextCloudFile.objects.filter(folder=self.folder, slug=self.slug).exclude(id=self.id).exists():
Fine as is, but this is essentially a [unique_together](https://docs.djangoproject.com/en/3.2/ref/models/options/#unique-together) on the slug and folder

2023-01-08 17:40 UTC, EricTRL commented on nextcloud_integration/forms.py
>          self.instance.connection = "NcS"
Might as well use the new value :)
```suggestion
        self.instance.connection = SquireNextCloudFile.CONNECTION_NEXTCLOUD_SYNC
```

2023-01-19 10:53 UTC, EricTRL requested changes

2023-01-19 10:53 UTC, EricTRL commented on nextcloud_integration/migrations/0001_initial.py
> +    replaces = [('nextcloud_integration', '0001_initial'), ('nextcloud_integration', '0002_auto_20220925_1758'), ('nextcloud_integration', '0003_ncfolder_slug'), ('nextcloud_integration', '0004_auto_
`replaces` also needs to be removed when the squashed-migration files themselves are also removed. See the last bullet point at the bottom of [this](https://docs.djangoproject.com/en/3.2/topics/migrations/#squashing-migrations) docs section.

>You must then transition the squashed migration to a normal migration by:
> - Deleting all the migration files it replaces.
>- Updating all migrations that depend on the deleted migrations to depend on the squashed migration instead.
>- Removing the **replaces** attribute in the **Migration** class of the squashed migration (this is how Django tells that it is a squashed migration).

2023-01-19 15:05 UTC, EricTRL approved these changes

2023-01-19 15:09 UTC, merged