Feature/meetings
esrg-knights/Squire pull request #304
Opened 2023-02-14 15:01 UTC by DutcherNL

A new feature to insert meetings into squire. This will be implemented for campaign planning

Still to do:
- [x] Redact is_public field (it is replaced with a choicefield)
- [x] Meeting calendar feed
- [x] Testcases

2023-03-31 11:42 UTC, EricTRL requested changes

2023-03-31 11:42 UTC, EricTRL commented on activity_calendar/constants.py
> +ACTIVITY_PUBLIC = "PUBLIC"
Consider making this an Enum?

2023-04-08 09:34 UTC, EricTRL approved these changes

2023-04-08 09:50 UTC, LenaWil requested changes
Friendly request to at least run the formatter on the files you added

It’s possible to do that offline.

If you really don’t want to or think the formatter is too strict, that’s okay too, but then we should talk about improving that.

https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html

2023-04-08 10:11 UTC, DutcherNL commented
> Friendly request to at least run the formatter on the files you added
Is there a way to run them all as a single commit. As you can see it has a lot of suggestions and I rather not gain RSI from formatting xD

2023-04-08 10:44 UTC, LenaWil commented
> 
> Is there a way to run them all as a single commit. As you can see it has a lot of suggestions and I rather not gain RSI from formatting xD
XD

Which IDE are you using?

2023-04-09 09:35 UTC, LenaWil reviewed
I sent #314, otherwise fine with me.

2023-04-09 10:41 UTC, LenaWil approved these changes

2023-04-09 10:50 UTC, merged